### ISSUE TITLE
<.Package>: can't evaluate field Package in type generator.GenSchema

### ISSUE THREAD

**Issue by Number1Tsar** [go-swagger/dockerctl#11]
Cant autogenerate files. Running the command

$ swagger generate cli --target=. --spec=https://raw.githubusercontent.com/docker/engine/master/api/swagger.yaml

returns this issue

2021/06/07 17:36:29 creating generated file "build_info_model.go" in "cli" as clidefinitionhook
failed rendering template data for clidefinitionhook: template execution failed for template clidefinitionhook: template: cliSchema:89:33: executing "modelschemacliinternal" at <.Package>: can't evaluate field Package in type generator.GenSchema

Env: go 1.14

Detailed Response:

❯ ~/go/bin/swagger generate cli --target=. --spec=https://raw.githubusercontent.com/docker/engine/master/api/swagger.yaml
2021/06/07 17:35:31 validating spec https://raw.githubusercontent.com/docker/engine/master/api/swagger.yaml
2021/06/07 17:36:18 preprocessing spec with option:  minimal flattening
2021/06/07 17:36:18 building a plan for generation
2021/06/07 17:36:18 generation target .
2021/06/07 17:36:18 planning definitions (found: 88)
2021/06/07 17:36:18 warn: properties with a default value or readOnly should not be required [RefCount]
2021/06/07 17:36:18 warn: properties with a default value or readOnly should not be required [Size]
2021/06/07 17:36:18 warn: properties with a default value or readOnly should not be required [Scope]
2021/06/07 17:36:19 planning operations (found: 106)
2021/06/07 17:36:27 grouping operations into packages (packages: 15)
2021/06/07 17:36:27 operations for package packages "system" (found: 7)
2021/06/07 17:36:27 operations for package packages "network" (found: 7)
2021/06/07 17:36:27 operations for package packages "container" (found: 25)
2021/06/07 17:36:27 operations for package packages "distribution" (found: 1)
2021/06/07 17:36:27 operations for package packages "plugin" (found: 11)
2021/06/07 17:36:27 operations for package packages "image" (found: 15)
2021/06/07 17:36:27 operations for package packages "exec" (found: 4)
2021/06/07 17:36:27 operations for package packages "volume" (found: 5)
2021/06/07 17:36:27 operations for package packages "task" (found: 3)
2021/06/07 17:36:27 operations for package packages "swarm" (found: 7)
2021/06/07 17:36:27 operations for package packages "node" (found: 4)
2021/06/07 17:36:27 operations for package packages "secret" (found: 5)
2021/06/07 17:36:27 operations for package packages "service" (found: 6)
2021/06/07 17:36:27 operations for package packages "session" (found: 1)
2021/06/07 17:36:27 operations for package packages "config" (found: 5)
2021/06/07 17:36:27 planning meta data and facades
2021/06/07 17:36:27 rendering 2 templates for model Address
2021/06/07 17:36:27 name field Address
2021/06/07 17:36:27 package field models
2021/06/07 17:36:27 creating generated file "address.go" in "models" as definition
2021/06/07 17:36:27 executed template asset:model
2021/06/07 17:36:27 name field Address
2021/06/07 17:36:27 package field models
2021/06/07 17:36:27 creating generated file "address_model.go" in "cli" as clidefinitionhook
2021/06/07 17:36:27 executed template asset:cliModelcli
2021/06/07 17:36:27 rendering 2 templates for model AuthConfig
2021/06/07 17:36:27 name field AuthConfig
2021/06/07 17:36:27 package field models
2021/06/07 17:36:27 creating generated file "auth_config.go" in "models" as definition
2021/06/07 17:36:27 executed template asset:model
2021/06/07 17:36:27 name field AuthConfig
2021/06/07 17:36:27 package field models
2021/06/07 17:36:27 creating generated file "auth_config_model.go" in "cli" as clidefinitionhook
2021/06/07 17:36:27 executed template asset:cliModelcli
2021/06/07 17:36:28 rendering 2 templates for model BuildCache
2021/06/07 17:36:28 name field BuildCache
2021/06/07 17:36:28 package field models
2021/06/07 17:36:28 creating generated file "build_cache.go" in "models" as definition
2021/06/07 17:36:28 executed template asset:model
2021/06/07 17:36:28 name field BuildCache
2021/06/07 17:36:28 package field models
2021/06/07 17:36:28 creating generated file "build_cache_model.go" in "cli" as clidefinitionhook
2021/06/07 17:36:28 executed template asset:cliModelcli
2021/06/07 17:36:29 rendering 2 templates for model BuildInfo
2021/06/07 17:36:29 name field BuildInfo
2021/06/07 17:36:29 package field models
2021/06/07 17:36:29 creating generated file "build_info.go" in "models" as definition
2021/06/07 17:36:29 executed template asset:model
2021/06/07 17:36:29 name field BuildInfo
2021/06/07 17:36:29 package field models
2021/06/07 17:36:29 creating generated file "build_info_model.go" in "cli" as clidefinitionhook
failed rendering template data for clidefinitionhook: template execution failed for template clidefinitionhook: template: cliSchema:89:33: executing "modelschemacliinternal" at <.Package>: can't evaluate field Package in type generator.GenSchema

**Comment by youyuanwu** [comment]
There is a bug on go-swagger 0.27.0 release.
If you build go-swagger from source on master branch, the generation should success.

**Comment by Number1Tsar** [comment]
Awesome! That worked. Thanks.
